# Makefile for pc21
#
# CSCI 21, Spring 2014
#
# Programmer: Jacob Slaton
#

FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for project 21
# Date completed: 4-21-2014
pc21: box.h pc21.cpp
	g++ $(FLAGS) pc21.cpp -o pc21
