# Makefile for pc22
#
# CSCI 21, Spring 2014
#
# Programmer: Jacob Slaton
#

FLAGS = -Wall -Wextra -Werror -pedantic -Wno-newline-eof

# Target for project 21
# Date completed: 4-23-2014
pc22: SLNode.h SList.h pc22.cpp
	g++ $(FLAGS) pc22.cpp -o pc22
